include:
  # Normal user scope.
  # submit_job can override this with SPACK_USER_CONFIG_PATH.
  - name: "user"
    path_override_env_var: SPACK_USER_CONFIG_PATH
    path: "~/.spack"
    optional: true
    prefer_modify: true
    when: '"SPACK_DISABLE_LOCAL_CONFIG" not in env'

  # Normal Pawsey site defaults.
  # This is what ordinary users get.
  - name: "site"
    path: "$spack/etc/spack/site"
    optional: true

  # Optional system scope.
  - name: "system"
    path_override_env_var: SPACK_SYSTEM_CONFIG_PATH
    path: "/etc/spack"
    optional: true
    when: '"SPACK_DISABLE_LOCAL_CONFIG" not in env'
