upstreams:
  # Project-wide installations are made visible to use-private spack commands to provide
  # dependencies. They are also listed before the system-wide upstream because 
  # project-wide installations may depend on system-wide ones.
  project_wide:
    install_tree: /software/projects/$PAWSEY_PROJECT/setonix/2026.05/software

  # this is the location of the system wide installation
  # it acts as an upstream installation for project-wide and user-specific installations
  system_wide:
    install_tree: /scratch/pawsey0001/ilkhom/2026.05/software

#  autoload+upstream currently does not work, 
# so better not to expose upstreams modules to user installations
#    modules:
#      lmod: /scratch/pawsey0001/ilkhom/2026.05/modules
