#!/bin/bash

SPACK_DIR=INSTALL_PREFIX/spack
REALSPACK="${SPACK_DIR}/bin/realspack"

if (( $# > 0 )) && [ "$1" = "project" ]; then
    # enable group access and writing to the stack
    if [ "$2" = "customise" ]; then
        pawsey_spack_customise.sh project ${3} ${4}
    else
        umask g+rwx
        ${REALSPACK} -C "${SPACK_DIR}/etc/spack/project" ${@:2}
    fi
else
    if [ "$1" = "customise" ]; then
        pawsey_spack_customise.sh user ${2} ${3}
    else
        ${REALSPACK} ${@}
    fi
fi

