# Copyright 2016-2022 Swiss National Supercomputing Centre (CSCS/ETH Zurich)
# ReFrame Project Developers. See the top-level LICENSE file for details.
#
# SPDX-License-Identifier: BSD-3-Clause


#
# This file was originally automatically generated by ReFrame based on 'setup_files/settings.py'.  # noqa: E501
# It has been modified by Edric to suit the quantum partition.
#

import os


def quantum_account():
    project = os.environ.get('PAWSEY_PROJECT')
    if project:
        if project.endswith('-q'):
            return project
        return f'{project}-q'

    return None


def quantum_access():
    access = ['--partition=quantum']
    account = quantum_account()
    if account:
        access.append(f'--account={account}')

    return access


def job_prerequisite_modules():
    gcc_version = os.environ.get('gcc_version', '13.3.1')
    pawseyenv_version = os.environ.get('pawseyenv_version', '2026.08')

    return [
        f'pawseyenv/{pawseyenv_version}',
        'PrgEnv-gnu',
        f'gcc-native/{gcc_version.split(".")[0]}',
        'craype-arm-grace',
    ]


site_configuration = {
    'systems': [
        {
            'name': 'setonix-q',
            'descr': 'Setonix-Q',
            'hostnames': [
                'setonix-01', 'setonix-02', 'setonix-03', 'setonix-04',
                'setonix-09', 'nid002248', 'nid002250', 'nid003016',
                'nid003018'
            ],
            'modules_system': 'lmod',
            'partitions': [
                {
                    'name': 'quantum',
                    'descr': 'Setonix-Q GH200 (compute nodes) partition',
                    'scheduler': 'slurm',
                    'launcher': 'srun',
                    'modules': [],
                    'access': quantum_access(),
                    'max_jobs': 16,
                    'environs': [
                        'PrgEnv-gnu',
                    ],
                    'resources': [
                        {
                            'name': 'gpu',
                            'options': ['--gres=gpu:{num_gpus_per_node}']
                        },
                        {
                            'name': 'gpu_nvme',
                            'options': ['--gres=gpu:{num_gpus_per_node},tmp:{nvme_gb}G']
                        }
                    ],
                    'processor': {
                        'num_cpus': 288,
                        'num_cpus_per_core': 1,
                        'num_cpus_per_socket': 72,
                        'num_sockets': 4
                    },
                },
                {
                    'name': 'quantum-shell',
                    'descr': 'Setonix-Q shell checks',
                    'scheduler': 'slurm',
                    'launcher': 'local',
                    'modules': [],
                    'access': quantum_access(),
                    'max_jobs': 1,
                    'environs': [
                        'PrgEnv-gnu',
                    ],
                    'resources': [
                        {
                            'name': 'gpu',
                            'options': ['--gres=gpu:{num_gpus_per_node}']
                        },
                    ],
                    'processor': {
                        'num_cpus': 288,
                        'num_cpus_per_core': 1,
                        'num_cpus_per_socket': 72,
                        'num_sockets': 4
                    },
                },
            ]
        },
    ],
    'environments': [
        {
            'name': 'PrgEnv-gnu',
            'target_systems': ['setonix-q'],
            # Pin gcc-native after PrgEnv-gnu; plain PrgEnv-gnu otherwise resets
            # GNU to the PE default.
            'modules': job_prerequisite_modules()
        },
    ],
    'logging': [
        {
            'level': 'debug',
            'handlers': [
                {
                    'type': 'file',
                    'name': 'reframe.log',
                    'level': 'debug',
                    'format': '[%(asctime)s] %(levelname)s: %(check_name)s: %(message)s',  # noqa: E501
                    'append': False
                },
                {
                    'type': 'stream',
                    'name': 'stdout',
                    'level': 'info',
                    'format': '%(message)s'
                },
                {
                    'type': 'file',
                    'name': 'reframe.out',
                    'level': 'info',
                    'format': '%(message)s',
                    'append': False
                }
            ],
            'handlers_perflog': [
                {
                    'type': 'filelog',
                    'prefix': '%(check_system)s/%(check_partition)s',
                    'level': 'info',
                    'format': '%(asctime)s|reframe %(version)s|%(check_info)s|jobid=%(check_jobid)s|%(check_perf_var)s=%(check_perf_value)s|ref=%(check_perf_ref)s (l=%(check_perf_lower_thres)s, u=%(check_perf_upper_thres)s)',  # noqa: E501
                    'append': True
                }
            ]
        }
    ],
    'modes': [
        {
            'name': 'maintenance',
            'options': [
                '--exec-policy=async',
                '--reservation=maintenance',
                '--save-log-files',
                '--tag=acceptance',
                '--timestamp=%F_%H-%M-%S'
            ]
        },
        {
            'name': 'production',
            'options': [
                '--exec-policy=async',
                '--strict',
                '--output=$APPS/UES/$USER/regression/production',
                '--logdir=$APPS/UES/$USER/regression/production/logs',
                '--stage=$SCRATCH/regression/production/stage',
                '--save-log-files',
                '--tag=production',
                '--timestamp=%F_%H-%M-%S'
            ]
        }
    ],
    'general': [
        {
            'check_search_path': [
                'checks/'
            ],
            'check_search_recursive': True
        }
    ]
}
