packages:
  all:
  # note the compiler and providers specifications
  # only suggest a priority order, they do not exclude other options
  # suggested priority for compilers.
    compiler: [ gcc@14.2.0, cce@19.0.0, aocc@5.0.0 ]
    providers:
      mpi: [ cray-mpich ]
      blas: [ openblas, amdblis ] #, cray-libsci ] # commenting out cray-libsci as bug was identified
      lapack: [ openblas, netlib-lapack, amdlibflame ] #, cray-libsci ]
      scalapack: [ netlib-scalapack, amdscalapack ] #, cray-libsci ]
      fftw-api: [ fftw, amdfftw ] #, cray-fftw ] # commenting out cray-fftw for now, similar to cray-libsci
      pkgconfig: [ pkg-config ]
    permissions:
      read: world
      # this should be user, we do not want pawsey0001 users 
      # to accidentally edit the system wide installation
      write: user
      # using default group
      # fine, considering world readable and user writable
      # could not use $PAWSEY_PROJECT, as variables are apparently not evaluated here

# don't build virtuals with an external provider
  mpi:
    buildable: false
# Left buildable, as currently built by Spack, 
# because cray-libsci and cray-fftw are not in use (see below)
#  blas:
#    buildable: false
#  lapack:
#    buildable: false
#  scalapack:
#    buildable: false
# FFTW non buildable, to avoid proliferation of variants, 
# that are ultimately a subset of the system-wide one (num_libs)
# Edit: FFTW buildable, otherwise in Spack 0.17.0 the concretiser crashes
#  fftw-api:
#    buildable: false
  pkgconfig:
    buildable: false
# don't build compilers neither
  cce:
    buildable: false
  gcc:
    buildable: false
  aocc:
    buildable: false
  intel:
    buildable: false
  pgi:
    buildable: false

  # GENERAL NOTES:
  # 1. for each package, only one entry must exist in this yaml
  # otherwise only the last one is considered, and the previous ones are ingored
  # 2. when externals are specified, the preferred version is respected only if it is one of the externals

  #TODO for next stack builds: consider adding more +pic as default variant

  # preferred versions and variants, dependencies
  # required by devel/hpctoolkit, but good to have for everything
  libunwind:
    variants: '+pic'
  mbedtls:
    variants: '+pic'
#  libseccomp:
#    version: [2.5.4]
  zlib:
    version: [1.3.1]
  zstd:
    version: [1.5.6]
  json-c:
    version: [0.16]
  krb5:
    version: [1.21.3]
  # cmake can have multiple entries so set default
  cmake:
    version: [3.30.5]
    variants: ~doc+ncurses+ownlibs~qt
# Commented out - see GENERAL NOTES above
#    externals:
#  # manual addition with the latest version
#    - spec: cmake@3.21.4
#      prefix: /lus/joey/home/mdelapierre/Spack-sprints/v0.17.0_new/spack/opt/spack/cray-sles15-zen2/gcc-10.3.0/cmake-3.21.4-dgyicf6mmctyfw2fdzeja2jt5jf5gzl5
#    - spec: cmake@3.10.2
#      prefix: /usr
  ffmpeg:
    version: [7.0.2]
  gnuplot:
    version: [6.0.0]
    variants: '+X'
  llvm:
    variants: '~omp_as_runtime ~clang ~compiler-rt ~polly ~gold'
  # preferred versions and variants, python
  python:
    version: [3.11.6]
    variants: '+optimizations +zlib ~ssl'
  gdbm:
    version: [1.24]
  apr:
    version: [1.7.5] #subversion needs older apr version
  gettext:
    version: [0.22.5]
  py-cython:
    version: [3.0.11]
  py-dask:
    version: [2024.7.1]
  py-h5py:
    version: [3.12.1]
  py-ipython:
    version: [8.28.0]
  py-matplotlib:
    version: [3.9.2]
    variants: '+movies'
  py-mpi4py:
    version: [4.0.1]
  py-numba:
    version: [0.58.1]
  py-numpy:
    version: [2.1.2]
  py-pandas:
    version: [2.2.3]
  py-pip:
    version: [23.1.2]
  py-plotly:
    version: [5.20.0]
  py-scikit-learn:
    version: [1.5.2]
  py-scipy:
    version: [1.14.1]
  py-setuptools:
    version: [59.4.0]
  # preferred versions and variants, compilers
  go:
    version: [1.23.2]
  julia:
     version: [1.11.0]
  openjdk:
    version: [17.0.8.1_1]
#    version: [21.0.3_9]
  r:
    version: [4.4.1]
# Commented out - see GENERAL NOTES above
#    externals:
#    - spec: r@4.0.5.1
#      prefix: /opt/cray/pe/R/4.0.5.1
  perl:
    version: [5.40.0]
# Commented out - see GENERAL NOTES above
#    externals:
#    - spec: perl@5.26.1~cpanm
#      prefix: /usr
  ruby:
    version: [3.3.5]
  # preferred versions and variants, num_libs
  amdblis:
    version: [5.0]
    variants: 'threads=openmp'
  amdlibflame:
    version: [5.0]
    variants: 'threads=openmp'
  amdscalapack:
    version: [5.0]
    variants: 'build_type=Release'
  aocl-sparse:
    version: [5.0]
    variants: 'build_type=Release'
  amdfftw:
    version: [5.0]
    variants: 'precision=float,double,long_double'
  amdlibm:
    version: [5.0]
  blaspp:
    version: [2024.10.26]
    variants: '~cuda build_type=Release'
  boost:
    version: [1.86.0]
    variants: '+mpi +numpy +python'
  eigen:
    version: [3.4.0]
    variants: 'build_type=Release'
  fftw:
    version: [3.3.10,2.1.5]
    variants: '+openmp precision=float,double,long_double'
  gsl:
    version: [2.8]
  hpx:
    version: [1.10.0]
    variants: '+async_mpi malloc=jemalloc max_cpu_count=128 networking=mpi cxxstd=14 build_type=Release'
  kokkos:
    version: [4.4.01]
    variants: '+hwloc +memkind +numactl +openmp +tuning cxxstd=14 build_type=Release'
  netlib-lapack:
    version: [3.11.0]
    variants: 'build_type=Release'
  openblas:
    version: [0.3.28]
    variants: 'threads=openmp'
  opencv:
     version: [4.10.0]
     variants: 'build_type=Release'
  plasma:
    version: [24.8.7]
    variants: 'build_type=Release'
  petsc:
    version: [3.22.1]
    variants: '+fftw' # commenting out trilinos as per environment note # +trilinos'
  plumed:
    version: [2.9.2]
  netlib-scalapack:
    version: [2.2.0]
  slate:
    version: [2024.10.29]
    variants: '~cuda build_type=Release'
  trilinos:
    version: [15.0.0]
    variants: '+adios2 +openmp +python build_type=Release'
# preferred versions and variants, io_libs
  hdf5:
    version: [1.14.5]
    variants: 'api=v112 +hl +fortran +szip build_type=Release'
  hdf:
    version: [4.2.15]
    variants: '+shared+external-xdr'
  adios2:
    version: [2.10.2]
    variants: '+python +hdf5 build_type=Release'
  netcdf-c:
    version: [4.9.2]
    variants: '+hdf4 +parallel-netcdf'
  netcdf-cxx:
    version: [4.2]
  netcdf-cxx4:
    version: [4.3.1]
  netcdf-fortran:
    version: [4.6.1]
  parallel-netcdf:
    version: [1.12.3]
  py-h5netcdf:
    version: [1.3.0]
  py-netcdf4:
    version: [1.6.5]
# for end users apps, prefer cmake variant build_type=Release
  caliper:
    variants: 'build_type=Release'
  gromacs:
    variants: 'build_type=Release'
  lammps:
    variants: 'build_type=Release'
  nektar:
    variants: 'build_type=Release'
  visit:
    variants: 'build_type=Release'

  #for astro packages prefer release
  casacore:
    variants: 'build_type=Release'
  everybeam:
    variants: 'build_type=Release'
  wsclean:
    variants: 'build_type=Release'
  idg:
    variants: 'build_type=Release'
  cghcentre:
    variants: 'build_type=Release'

  # ===========================================================================
  #                                  EXTERNALS
  # ===========================================================================
  pkg-config:
    externals:
    - spec: pkg-config@0.29.2
      prefix: /usr
    buildable: false

  hwloc:
    externals:
    - spec: hwloc@2.9.0
      prefix: /usr
    buildable: false

  numactl:
    externals:
    - spec: numactl@2.0.14
      prefix: /usr
    buildable: false

  pcre:
    externals:
    - spec: pcre2@10.42
      prefix: /usr
    buildable: false

  libssh:
    externals:
    - spec: libssh@4.8.9
      prefix: /usr
    buildable: false

#  rust:
#    externals:
#    - spec: rust@1.84.1
#      prefix: /software/setonix/2025.02/software/linux-sles15-zen3/gcc-13.3.0/rust-1.84.1/toolchains/stable-x86_64-unknown-linux-gnu
#    buildable: false

  libseccomp:
    externals:
    - spec: libseccomp@2.5.3
      prefix: /usr
    buildable: false

  libgcrypt:
    externals:
    - spec: libgcrypt@1.10.3
      prefix: /usr
    buildable: false

# ----------------------------------------------------------------------------
#                                        CRAY
# ----------------------------------------------------------------------------
  lustre:
    externals:
    - spec: lustre@2.15.5.2_cray_1_g9231caa
      prefix: /usr
    buildable: false

  # adding prefixes as in NERSC Perlmutter configs
  # -----
  # MPI and communication related externals 
  # ----- 
  cray-mpich:
    externals:
    - spec: cray-mpich@8.1.32%gcc
      modules:
      - cray-mpich/8.1.32
      - craype-network-ofi
      prefix: /opt/cray/pe/mpich/8.1.32/ofi/gnu/12.3
    - spec: cray-mpich@8.1.32%cce
      modules:
      - cray-mpich/8.1.32
      - craype-network-ofi
      prefix: /opt/cray/pe/mpich/8.1.32/ofi/crayclang/17.0
    - spec: cray-mpich@8.1.32%aocc
      modules:
      - cray-mpich/8.1.32
      - craype-network-ofi
      prefix: /opt/cray/pe/mpich/8.1.32/ofi/aocc/4.1
    buildable: false

  cray-pmi:
    externals:
    - spec: cray-pmi@6.1.15
      modules:
      - cray-pmi/6.1.15
    buildable: false

  xpmem:
    externals:
    - spec: xpmem@2.11.3
      modules:
      - xpmem/2.11.3-1.3_gdbda01a1eb3d 
      prefix: /opt/cray/xpmem/2.11.3-1.3_gdbda01a1eb3d
    buildable: false

  # libraries related to libfabric and mpi 
  libfabric:
    externals:
    - spec: libfabric@1.22.0
      modules:
      - libfabric/1.22.0
      prefix: /opt/cray/libfabric/1.22.0
    buildable: false

  openssl:
    externals:
    - spec: openssl@3.1.4
      prefix: /usr
    buildable: false

  brotli:
    externals:
    - spec: brotli@1.0.7
      prefix: /usr
    buildable: false

  curl:
    externals:
    - spec: curl@8.6.0
      prefix: /usr
    buildable: false

  openssh:
    externals:
    - spec: openssh@9.6p1
      prefix: /usr
    buildable: false

  keyutils:
    externals:
    - spec: keyutils@1.6.3
      prefix: /usr
    buildable: false

  cryptopp:
    externals:
    - spec: cryptopp@8.6.0
      prefix: /usr
    buildable: false

  openldap:
    externals:
    - spec: openldap2@2.4.46
      prefix: /usr
    buildable: false

  libpsl:
    externals:
    - spec: libpsl@0.20.1
      prefix: /usr
    buildable: false

  nghttp2:
    externals:
    - spec: nghttp2@1.40.0
      prefix: /usr
    buildable: false

  libidn2:
    externals:
    - spec: libidn2@2.2.0
      prefix: /usr
    buildable: false

  libyaml:
    externals:
    - spec: libyaml@0.1.7
      prefix: /usr
    buildable: false
  # ----- 
  # other external packages not related to communication
  # -----
  papi:
    externals:
    - spec: papi@7.2.0.1
      modules:
      - papi/7.2.0.1
      prefix: /opt/cray/pe/papi/7.2.0.1
    buildable: false
# Cray-LibSci: commenting out, as bug was identified (21 December 2021)
  cray-libsci:
    externals:
    - spec: cray-libsci@25.03.0%gcc
      modules:
      - cray-libsci/25.03.0
      prefix: /opt/cray/pe/libsci/24.07.0/GNU/12.3/x86_64
    - spec: cray-libsci@25.03.0%cce
      modules:
      - cray-libsci/25.03.0
      prefix: /opt/cray/pe/libsci/25.03.0/CRAYCLANG/17.0/x86_64
    #- spec: cray-libsci@23.09.1.1%aocc
    #  modules:
    #  - cray-libsci/23.09.1.1
    #  prefix: /opt/cray/pe/libsci/23.09.1.1/aocc/2.0/x86_64
    buildable: false
# Cray-FFTW: commenting out, as for Cray-Libsci
  cray-fftw:
    externals:
    - spec: cray-fftw@3.3.10.10 target=zen3
      modules:
      - craype-x86-milan
      - cray-fftw/3.3.10.10
      prefix: /opt/cray/pe/fftw/3.3.10.10/x86_milan
    buildable: false


# =====================================================================
#                       ROCM EXTERNALS
# =====================================================================

  rocm-bandwidth-test:
      buildable: false
      externals:
      - spec: rocm-bandwidth-test@6.3.0
        prefix: /opt/rocm-6.3.0


  rocm-opencl:
      buildable: false
      externals:
      - spec: rocm-opencl@6.3.0
        prefix: /opt/rocm-6.3.0


  hipsparse:
      buildable: false
      externals:
      - spec: hipsparse@6.3.0
        prefix: /opt/rocm-6.3.0


  atmi:
      buildable: false

  rocm-clang-ocl:
      buildable: false
      externals:
      - spec: rocm-clang-ocl@6.3.0
        prefix: /opt/rocm-6.3.0


  llvm-amdgpu:
      buildable: false
      externals:
      - spec: llvm-amdgpu@6.3.0
        prefix: /opt/rocm-6.3.0


  hipfort:
      buildable: false

  hsa-rocr-dev:
      buildable: false
      externals:
      - spec: hsa-rocr-dev@6.3.0
        prefix: /opt/rocm-6.3.0


  hip-rocclr:
      buildable: false
      externals:
      - spec: hip-rocclr@6.3.0
        prefix: /opt/rocm-6.3.0


  roctracer-dev-api:
      buildable: false
      externals:
      - spec: roctracer-dev-api@6.3.0
        prefix: /opt/rocm-6.3.0


  rocm-smi:
      buildable: false
      externals:
      - spec: rocm-smi@6.3.0
        prefix: /opt/rocm-6.3.0


  rocrand:
      buildable: false
      externals:
      - spec: rocrand@6.3.0
        prefix: /opt/rocm-6.3.0


  rocm-cmake:
      buildable: false
      externals:
      - spec: rocm-cmake@6.3.0
        prefix: /opt/rocm-6.3.0


  rocfft:
      buildable: false
      externals:
      - spec: rocfft@6.3.0
        prefix: /opt/rocm-6.3.0


  rocm-device-libs:
      buildable: false
      externals:
      - spec: rocm-device-libs@6.3.0
        prefix: /opt/rocm-6.3.0


  hipfft:
      buildable: false
      externals:
      - spec: hipfft@6.3.0
        prefix: /opt/rocm-6.3.0


  rocthrust:
      buildable: false
      externals:
      - spec: rocthrust@6.3.0
        prefix: /opt/rocm-6.3.0


  rocprofiler-dev:
      buildable: false
      externals:
      - spec: rocprofiler-dev@6.3.0
        prefix: /opt/rocm-6.3.0


  rocalution:
      buildable: false
      externals:
      - spec: rocalution@6.3.0
        prefix: /opt/rocm-6.3.0


  rocm-debug-agent:
      buildable: false
      externals:
      - spec: rocm-debug-agent@6.3.0
        prefix: /opt/rocm-6.3.0


  hipblas:
      buildable: false
      externals:
      - spec: hipblas@6.3.0
        prefix: /opt/rocm-6.3.0


  rocm-gdb:
      buildable: false
      externals:
      - spec: rocm-gdb@6.3.0
        prefix: /opt/rocm-6.3.0


  hipify-clang:
      buildable: false
      externals:
      - spec: hipify-clang@6.3.0
        prefix: /opt/rocm-6.3.0


  rocprim:
      buildable: false
      externals:
      - spec: rocprim@6.3.0
        prefix: /opt/rocm-6.3.0


  hsakmt-roct:
      buildable: false
      externals:
      - spec: hsakmt-roct@6.3.0
        prefix: /opt/rocm-6.3.0


  roctracer-dev:
      buildable: false
      externals:
      - spec: roctracer-dev@6.3.0
        prefix: /opt/rocm-6.3.0


  hipcub:
      buildable: false
      externals:
      - spec: hipcub@6.3.0
        prefix: /opt/rocm-6.3.0


  rocm-smi-lib:
      buildable: false
      externals:
      - spec: rocm-smi-lib@6.3.0
        prefix: /opt/rocm-6.3.0


  rocwmma:
      buildable: false
      externals:
      - spec: rocwmma@6.3.0
        prefix: /opt/rocm-6.3.0


  rocm-openmp-extras:
      buildable: false
      externals:
      - spec: rocm-openmp-extras@6.3.0
        prefix: /opt/rocm-6.3.0


  rocm-core:
      buildable: false
      externals:
      - spec: rocm-core@6.3.0
        prefix: /opt/rocm-6.3.0

  comgr:
      buildable: false
      externals:
      - spec: comgr@6.3.0
        prefix: /opt/rocm-6.3.0


  rocblas:
      buildable: false
      externals:
      - spec: rocblas@6.3.0
        prefix: /opt/rocm-6.3.0


  rccl:
      buildable: false
      externals:
      - spec: rccl@6.3.0
        prefix: /opt/rocm-6.3.0


  rocminfo:
      buildable: false
      externals:
      - spec: rocminfo@6.3.0
        prefix: /opt/rocm-6.3.0


  hip:
      buildable: false
      externals:
      - spec: hip@6.3.0
        prefix: /opt/rocm-6.3.0

  miopen-hip:
      buildable: false
      externals:
      - spec: miopen-hip@6.3.0
        prefix: /opt/rocm-6.3.0

  hiprand:
      buildable: false
      externals:
      - spec: hiprand@6.3.0
        prefix: /opt/rocm-6.3.0

  rocsparse:
      buildable: false
      externals:
      - spec: rocsparse@6.3.0
        prefix: /opt/rocm-6.3.0


  rocsolver:
      buildable: false
      externals:
      - spec: rocsolver@6.3.0
        prefix: /opt/rocm-6.3.0


  rocm-dbgapi:
      buildable: false
      externals:
      - spec: rocm-dbgapi@6.3.0
        prefix: /opt/rocm-6.3.0


  hipsolver:
      buildable: false
      externals:
      - spec: hipsolver@6.3.0
        prefix: /opt/rocm-6.3.0

