#!/bin/bash

module load plumed/2.7.2 netcdf-cxx4/4.3.1 hdf5/1.12.1-parallel-api-v112  rocm/5.0.2 fftw/3.3.9 cmake/3.21.4 adios2/2.7.1-hdf5 ffmpeg/4.4 eigen/3.4.0 kokkos/3.7.01-rocm

module load openblas/0.3.15
export INSTALL_DIR=/software/setonix/2022.11/custom/software/zen3/gcc/12.1.0/lammps-amd-gfx908/28Mar2023
#wget https://github.com/lanl/LATTE/archive/v1.2.2.tar.gz
#tar xf v1.2.2.tar.gz
export FFLAGS=-fPIC
export CXXFLAGS=-fPIC

#cd LATTE-1.2.2
#mkdir build
#cd build
#cmake -DCMAKE_INSTALL_PREFIX=$INSTALL_DIR -DCMAKE_BUILD_TYPE=Release ../cmake
#make VERBOSE=1 -j 12
#make install
#cd ../../
rm build -r
mkdir build
cd build

#'-DPKG_KIM=ON'
#-DUSE_INTERNAL_LINALG=on 
# -DMPI_CXX_LIBRARIES="-L${MPICH_DIR}/lib -lmpi -L${CRAY_MPICH_ROOTDIR}/gtl/lib -lmpi_gtl_hsa" 
export LDFLAGS="-L${MPICH_DIR}/lib -lmpi"
export CFLAGS="-I/${MPICH_DIR}/include -L${MPICH_DIR}/lib -lmpi -fPIC -lm"
export CXXFLAGS="-std=c++11 -I/${MPICH_DIR}/include -L${MPICH_DIR}/lib -fPIC -lmpi -lm"
 'cmake' '-G' 'Unix Makefiles' -DMPI_mpi_LIBRARY=${MPICH_DIR}/lib/libmpi.so -DMPI_C_LIB_NAMES=mpi -DMPI_CXX_LIB_NAMES=mpi -DCMAKE_PREFIX_PATH=$INSTALL_DIR -DCMAKE_INSTALL_PREFIX=$INSTALL_DIR -DCMAKE_CXX_STANDARD=11  -C /scratch/pawsey0001/spack/build_lammps/lammps-28Mar2023/cmake/presets/hip_amd.cmake -DCMAKE_CXX_COMPILER=hipcc -DMPI_CXX_COMPILER=CC -DCMAKE_Fortran_COMPILER=ftn -DCMAKE_C_COMPILER=hipcc -DMPI_C_COMPILER=cc -DCMAKE_CXX_FLAGS="-L${MPICH_DIR}/lib -lmpi -L${CRAY_MPICH_ROOTDIR}/gtl/lib -lmpi_gtl_hsa" -DHIP_ARCH=gfx90a -DBUILD_SHARED_LIBS:BOOL=ON '-DLAMMPS_EXCEPTIONS:BOOL=OFF' '-DBUILD_MPI=ON' '-DBUILD_OMP:BOOL=ON' '-DENABLE_TESTING=OFF' '-DPKG_GPU=OFF' '-DBUILD_LIB=ON' '-DWITH_JPEG:BOOL=ON' '-DWITH_PNG:BOOL=ON' '-DWITH_FFMPEG:BOOL=ON' '-DPKG_ASPHERE=ON' '-DPKG_BODY=ON' '-DPKG_BPM=OFF' '-DPKG_CLASS2=ON' '-DPKG_COLLOID=ON' '-DPKG_COMPRESS=ON' '-DPKG_CORESHELL=ON' '-DPKG_DIELECTRIC=ON' '-DPKG_DIPOLE=ON' '-DPKG_ELECTRODE=OFF' '-DPKG_GRANULAR=ON' '-DPKG_KSPACE=ON' '-DPKG_KOKKOS=ON' '-DPKG_LATTE=ON' '-DPKG_MANYBODY=ON' '-DPKG_MC=ON' '-DPKG_MEAM=ON' '-DPKG_MISC=ON' '-DPKG_MLIAP=OFF' '-DPKG_ML-IAP=ON' '-DPKG_ML-SNAP=ON' '-DPKG_MOLECULE=ON' '-DPKG_MPIIO=ON' '-DPKG_OPT=ON' '-DPKG_PERI=ON' '-DPKG_PLUGIN=ON' '-DPKG_POEMS=ON' '-DPKG_PYTHON=ON' '-DPKG_QEQ=ON' '-DPKG_REPLICA=ON' '-DPKG_RIGID=ON' '-DPKG_SHOCK=ON' '-DPKG_SNAP=OFF' '-DPKG_SPIN=ON' '-DPKG_SRD=ON' '-DPKG_VORONOI=ON' '-DPKG_USER-ATC=OFF' '-DPKG_USER-ADIOS=OFF' '-DPKG_USER-AWPMD=OFF' '-DPKG_USER-BOCS=OFF' '-DPKG_USER-BROWNIAN=OFF' '-DPKG_USER-CGSDK=OFF' '-DPKG_USER-COLVARS=OFF' '-DPKG_USER-DIFFRACTION=OFF' '-DPKG_USER-DPD=OFF' '-DPKG_USER-DRUDE=OFF' '-DPKG_USER-EFF=OFF' '-DPKG_USER-FEP=OFF' '-DPKG_USER-H5MD=OFF' '-DPKG_USER-LB=OFF' '-DPKG_USER-MANIFOLD=OFF' '-DPKG_USER-MEAMC=OFF' '-DPKG_USER-MESODPD=OFF' '-DPKG_USER-MESONT=OFF' '-DPKG_USER-MGPT=OFF' '-DPKG_USER-MISC=OFF' '-DPKG_USER-MOFFF=OFF' '-DPKG_USER-MOLFILE=OFF' '-DPKG_USER-NETCDF=OFF' '-DPKG_USER-OMP=OFF' '-DPKG_USER-PHONON=OFF' '-DPKG_USER-PLUMED=OFF' '-DPKG_USER-PTM=OFF' '-DPKG_USER-QTB=OFF' '-DPKG_USER-REACTION=OFF' '-DPKG_USER-REAXC=OFF' '-DPKG_USER-SDPD=OFF' '-DPKG_USER-SMD=OFF' '-DPKG_USER-SMTBQ=OFF' '-DPKG_USER-SPH=OFF' '-DPKG_USER-TALLY=OFF' '-DPKG_USER-UEF=OFF' '-DPKG_USER-YAFF=OFF' '-DPKG_ATC=ON' '-DPKG_ADIOS=ON' '-DPKG_AWPMD=ON' '-DPKG_BOCS=ON' '-DPKG_BROWNIAN=ON' '-DPKG_CG-SDK=ON' '-DPKG_COLVARS=ON' '-DPKG_DIFFRACTION=ON' '-DPKG_DPD-BASIC=ON' '-DPKG_DPD-MESO=ON' '-DPKG_DPD-REACT=ON' '-DPKG_DPD-SMOOTH=ON' '-DPKG_DRUDE=ON' '-DPKG_EFF=ON' '-DPKG_EXTRA-COMPUTE=ON' '-DPKG_EXTRA-DUMP=ON' '-DPKG_EXTRA-FIX=ON' '-DPKG_EXTRA-MOLECULE=ON' '-DPKG_EXTRA-PAIR=ON' '-DPKG_FEP=ON' '-DPKG_H5MD=ON' '-DPKG_INTERLAYER=ON' '-DPKG_LATBOLTZ=ON' '-DPKG_MACHDYN=ON' '-DPKG_MANIFOLD=ON' '-DPKG_MESONT=ON' '-DPKG_MGPT=ON' '-DPKG_MOFFF=ON' '-DPKG_MOLFILE=ON' '-DPKG_NETCDF=ON' '-DPKG_OPENMP=ON' '-DPKG_ORIENT=ON' '-DPKG_PHONON=ON' '-DPKG_PLUMED=ON' '-DPKG_PTM=ON' '-DPKG_QTB=ON' '-DPKG_REACTION=ON' '-DPKG_REAXFF=ON' '-DPKG_SMTBQ=ON' '-DPKG_SPH=ON' '-DPKG_TALLY=ON' '-DPKG_UEF=ON' '-DPKG_YAFF=ON'  '-DFFT=FFTW3' '-DEXTERNAL_KOKKOS=ON' '-DADIOS2_DIR=/software/setonix/2022.11/software/cray-sles15-zen3/gcc-12.1.0/adios2-2.7.1-j5hpkpsne5tbpnnnrs2qehqr4gceybot' '-DDOWNLOAD_PLUMED=no' '-DPLUMED_MODE=shared' '-DDOWNLOAD_EIGEN3=no' '-DEIGEN3_INCLUDE_DIR=/software/setonix/2022.11/software/cray-sles15-zen3/gcc-12.1.0/eigen-3.4.0-okxgiupkwfglk7vahgxbou3ertk5ptpl/include' /scratch/pawsey0001/spack/build_lammps/lammps-28Mar2023/cmake

make -j 128 
