# Copyright 2026 Pawsey Supercomputing Centre
#
# SPDX-License-Identifier: BSD-3-Clause
#
# Pawsey-developed recipe for the IBM Cloud SDK core, a runtime dependency of
# the Qiskit IBM Runtime client pulled in by the PennyLane-Qiskit plugin.

from spack.package import *


class PyIbmCloudSdkCore(PythonPackage):
    """Core library used by Python SDKs generated by the IBM OpenAPI SDK generator."""

    homepage = "https://github.com/IBM/python-sdk-core"
    url = "https://files.pythonhosted.org/packages/53/28/2d6e92262e81c3596c5567866d571c29461aa5afda2e2c72410083538a7b/ibm_cloud_sdk_core-3.25.0.tar.gz"

    license("Apache-2.0")

    version("3.25.0", sha256="33a193eed3dbbc02dabc371ceb4051d1f63a2742d38d57135d4775bc38aac76f")

    depends_on("python@3.10:", type=("build", "run"))
    depends_on("py-setuptools@67.7.2:", type="build")

    depends_on("py-requests@2.32.4:2", type=("build", "run"))
    depends_on("py-urllib3@2.4:2", type=("build", "run"))
    depends_on("py-python-dateutil@2.9:2", type=("build", "run"))
    depends_on("py-pyjwt@2.11:2", type=("build", "run"))
