# Copyright 2026 Pawsey Supercomputing Centre
#
# SPDX-License-Identifier: BSD-3-Clause
#
# Pawsey-developed recipe for the IBM Cloud SDK core, a runtime dependency of
# the Qiskit IBM Runtime client pulled in by the PennyLane-Qiskit plugin.
#
# Pawsey: pinned to the 3.16 series, the newest line whose leaf requirements
# (PyJWT>=2.4, urllib3<2.0) are satisfiable by the Spack 0.23.1 builtin
# repository on setonix-q.

from spack.package import *


class PyIbmCloudSdkCore(PythonPackage):
    """Core library used by Python SDKs generated by the IBM OpenAPI SDK generator."""

    homepage = "https://github.com/IBM/python-sdk-core"
    url = "https://files.pythonhosted.org/packages/71/7b/ddd443dc34702933e264fd0c00649612fc2bd588701f36503ec73d4de9dd/ibm-cloud-sdk-core-3.16.7.tar.gz"

    license("Apache-2.0")

    version("3.16.7", sha256="a985f147e8d78cc7eaaf127ada3e5da37dc46e37dea184aaf8878caced781674")

    depends_on("python@3.8:", type=("build", "run"))
    depends_on("py-setuptools", type="build")

    depends_on("py-requests@2.31:2", type=("build", "run"))
    depends_on("py-urllib3@1.26:1", type=("build", "run"))
    depends_on("py-python-dateutil@2.5.3:2", type=("build", "run"))
    depends_on("py-pyjwt@2.4:2", type=("build", "run"))
